import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process'

const LUCIDE_REPO_URL = 'https://github.com/lucide-icons/lucide.git';
const LUCIDE_REPO_DIR = './repo-lucide';
const LUCIDE_ICONS_DIR = path.join(LUCIDE_REPO_DIR, 'icons');

const LUCIDE_LAB_REPO_URL = 'https://github.com/lucide-icons/lucide-lab.git';
const LUCIDE_LAB_REPO_DIR = './repo-lucide-lab';
const LUCIDE_LAB_ICONS_DIR = path.join(LUCIDE_LAB_REPO_DIR, 'icons');

// OCaml reserved keywords that need to be suffixed with underscore
const OCAML_KEYWORDS = new Set([
  'and', 'as', 'assert', 'asr', 'begin', 'class', 'constraint', 'do', 'done',
  'downto', 'else', 'end', 'exception', 'external', 'false', 'for', 'fun',
  'function', 'functor', 'if', 'in', 'include', 'inherit', 'initializer',
  'land', 'lazy', 'let', 'lor', 'lsl', 'lsr', 'lxor', 'match', 'method',
  'mod', 'module', 'mutable', 'new', 'nonrec', 'object', 'of', 'open', 'or',
  'private', 'rec', 'sig', 'struct', 'then', 'to', 'true', 'try', 'type',
  'val', 'virtual', 'when', 'while', 'with'
]);

// Converts all whitespace into a single space for brevity when copied into OCaml.
function normalizeWhitespace(str) {
  return str.replace(/\n/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function parseIconsFromDirectory(iconsDir) {
  const svgFiles = fs.readdirSync(iconsDir)
    .filter(file => file.endsWith('.svg'))
    .sort();

  const icons = [];
  for (const file of svgFiles) {
    const name = file.replace('.svg', '');
    let functionName = name.replace(/-/g, '_');
    // Suffix with underscore if it's an OCaml keyword
    if (OCAML_KEYWORDS.has(functionName)) {
      functionName = functionName + '_';
    }
    const svgContent = fs.readFileSync(path.join(iconsDir, file), 'utf-8');

    // Extract inner SVG content (remove outer <svg> tag)
    const match = svgContent.match(/<svg[^>]*>(.*?)<\/svg>/s);
    if (match) {
      const innerContent = match[1].trim();
      icons.push({ name, functionName, innerContent });
    } else {
      console.warn(`Warning: Could not parse ${file}.`);
    }
  }

  return icons;
}

function parseIcons() {
  console.log('Parsing icons from lucide...');
  const lucideIcons = parseIconsFromDirectory(LUCIDE_ICONS_DIR);
  console.log(`Found ${lucideIcons.length} icons from lucide`);

  console.log('Parsing icons from lucide-lab...');
  const lucideLabIcons = parseIconsFromDirectory(LUCIDE_LAB_ICONS_DIR);
  console.log(`Found ${lucideLabIcons.length} icons from lucide-lab`);

  // Combine icons, with lucide icons taking precedence if there are duplicates
  const iconMap = new Map();

  for (const icon of lucideIcons) {
    iconMap.set(icon.functionName, icon);
  }

  for (const icon of lucideLabIcons) {
    if (iconMap.has(icon.functionName)) {
      console.log(`[${icon.functionName}] exists in both repos, using lucide version`);
    } else {
      iconMap.set(icon.functionName, icon);
    }
  }

  return Array.from(iconMap.values()).sort((a, b) =>
    a.functionName.localeCompare(b.functionName)
  );
}

function getMliContent(icons) {
  return `(* This file is automatically generated by [./generate.js] *)

open! Core
open! Virtual_dom

(** Lucide icons as Bonsai_web_icons. *)

${icons.map(icon => `val ${icon.functionName} : Bonsai_web_icon.t`).join('\n')}
`;
}

function getMlContent(icons) {
  const mlHeader = `(* This file is automatically generated by [./generate.js] *)

open! Core
open! Virtual_dom

let create ~name svg_path =
  Bonsai_web_icon.Expert.create ~name ~view_box_dimension:24 ~color_property:\`Stroke ~svg_path
;;

`;

  const mlFunctions = icons.map(icon => {
    const normalizedContent = normalizeWhitespace(icon.innerContent);
    return `\
let ${icon.functionName} =
  create
    ~name:"${icon.functionName}"
    {|${normalizedContent}|}
;;`;
  }).join('\n\n');

  return mlHeader + mlFunctions + '\n';
}

// Convert snake_case to Title_case for variant constructors
function toVariantName(functionName) {
  return functionName.charAt(0).toUpperCase() + functionName.slice(1);
}

function getEnumeratedMlContent(icons) {
  const variants = icons.map(icon => `  | ${toVariantName(icon.functionName)}`).join('\n');

  const matchCases = icons.map(icon =>
    `  | ${toVariantName(icon.functionName)} -> Lucide.${icon.functionName}`
  ).join('\n');

  return `(* This file is automatically generated by [../generate.js] *)

open! Core

(* This file contains a variant type for enumerating Lucide icons. *)

(* WARNING: Depending on this lib will cause every Lucide icon to be included in your
   build output, which will likely harm performance. Instead use [Lucide] directly. *)

module Private = struct
  type t =
    ${variants}
  [@@deriving enumerate]

  let to_icon = function
    ${matchCases}
  ;;
end
`;
}

// Main execution
console.log('Cloning lucide repository...');
execSync(`git clone --depth 1 ${LUCIDE_REPO_URL} ${LUCIDE_REPO_DIR}`, { stdio: 'inherit' });

console.log('Cloning lucide-lab repository...');
execSync(`git clone --depth 1 ${LUCIDE_LAB_REPO_URL} ${LUCIDE_LAB_REPO_DIR}`, { stdio: 'inherit' });

console.log('Reading SVG files...');
const icons = parseIcons();
console.log(`Total combined icons: ${icons.length}`);

console.log('Generating lucide.mli...');
fs.writeFileSync('lucide.mli', getMliContent(icons));

console.log('Generating lucide.ml...');
fs.writeFileSync('lucide.ml', getMlContent(icons));

console.log('Generating enumerated/lucide_enumerated.ml...');
fs.writeFileSync('enumerated/lucide_enumerated.ml', getEnumeratedMlContent(icons));

console.log('Copying LICENSE from lucide...');
const licenseSrc = path.join(LUCIDE_REPO_DIR, 'LICENSE');
const licenseDst = './LICENSE';
if (fs.existsSync(licenseSrc)) {
  fs.copyFileSync(licenseSrc, licenseDst);
} else {
  console.warn('Warning: LICENSE file not found in lucide repository');
}

console.log('Cleaning up...');
execSync(`rm -rf ${LUCIDE_REPO_DIR} ${LUCIDE_LAB_REPO_DIR}`, { stdio: 'inherit' });

console.log('Done! Generated:');
console.log('  - lucide.ml');
console.log('  - lucide.mli');
console.log('  - enumerated/lucide_enumerated.ml');
console.log('  - LICENSE');
console.log(`Total icons: ${icons.length}`);
